apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openclaw-helm.fullname" . }}
  labels:
    {{- include "openclaw-helm.labels" . | nindent 4 }}
data:
  openclaw.json: |
{{ .Values.config | toJson | indent 4 }}
  bash_aliases: |
    alias openclaw='node /app/dist/index.js'
