{{- if .Values.gateway.token.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openclaw-helm.fullname" . }}-gateway-token
  labels:
    {{- include "openclaw-helm.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  OPENCLAW_GATEWAY_TOKEN: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
